# Set caching headers for image files
seo:
  image:
    cache_control: "max-age=259200" # cache for 3 days

# Set caching headers for font files
asset_cache:
  max_age: 31536000 # cache for 1 year
  include:
    - "*.woff"
    - "*.woff2"

# Set caching headers for CSS files
assets:
  css:
    cache: true
    cache_control: "max-age=86400" # cache for 1 day
